<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>Hyperion</groupId>
  <artifactId>Studios</artifactId>
  <version>0.2.0-PreBuild</version>
  <name>The After Last Day</name>
  <description>The game isn't about how you survived the apocalypse; it's about how you died. Set in a zombie-infested rural county, the goal is to survive as long as possible. The atmosphere is tense, realistic, and unforgiving. The danger comes not only from the undead, but also from hunger, thirst, disease, isolation, and the desperate need for resources.</description>
  
  <properties>
	<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
    <lwjgl.version>2.9.3</lwjgl.version>
    <lwjgl.platform>windows</lwjgl.platform>
  </properties>
  
  <build>
    <sourceDirectory>src</sourceDirectory>
    <resources>
      <resource>
        <directory>src</directory>
        <excludes>
          <exclude>**/*.java</exclude>
        </excludes>
      </resource>
    </resources>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.8.1</version>
        <configuration>
          <source>${maven.compiler.source}</source>
          <target>${maven.compiler.target}</target>
        </configuration>
      </plugin>
      <plugin>
          <artifactId>maven-assembly-plugin</artifactId>
          <version>3.3.0</version>
          <configuration>
              <archive>
                  <manifest>
                      <addClasspath>true</addClasspath>
                      <mainClass>HyperionStudios.Game.Main</mainClass>
                  </manifest>
              </archive>
              <descriptorRefs>
                  <descriptorRef>jar-with-dependencies</descriptorRef>
              </descriptorRefs>
          </configuration>
          <executions>
              <execution>
                  <id>make-assembly</id>
                  <phase>package</phase>
                  <goals>
                      <goal>single</goal>
                  </goals>
              </execution>
          </executions>
      </plugin>
      
      <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-dependency-plugin</artifactId>
          <version>3.1.2</version>
          <executions>
              <execution>
                  <id>copy-natives</id>
                  <phase>generate-resources</phase>
                  <goals>
                      <goal>copy-dependencies</goal>
                  </goals>
                  <configuration>
                      <outputDirectory>${project.build.directory}/natives</outputDirectory>
                      <includeArtifactIds>lwjgl-platform</includeArtifactIds>
                      <stripVersion>true</stripVersion>
                  </configuration>
              </execution>
          </executions>
      </plugin>
    </plugins>
  </build>
  
  <dependencies>
        <dependency>
            <groupId>org.lwjgl.lwjgl</groupId>
            <artifactId>lwjgl</artifactId>
            <version>${lwjgl.version}</version>
        </dependency>
        
        <dependency>
            <groupId>org.lwjgl.lwjgl</groupId>
            <artifactId>lwjgl_util</artifactId>
            <version>${lwjgl.version}</version>
        </dependency>
        
        <dependency>
            <groupId>org.lwjgl.lwjgl</groupId>
            <artifactId>lwjgl-platform</artifactId>
            <version>${lwjgl.version}</version>
            <classifier>natives-${lwjgl.platform}</classifier>
            <scope>runtime</scope>
        </dependency>
        
  </dependencies>
</project>